---
- name: Agent Installation
  hosts: all
  user: centos
  become: yes
  become_method: sudo
  tasks:
  - name: install telnet
    package:
      name: telnet
      state: present          #absent     latest

  - name: Second task
    user:
      name: bob
      state: present

  - name: Add Admin Group
    group:
      name: admin
      state: present